DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  image TEXT,
  cover TEXT,
  fullname TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  phone TEXT,
  education TEXT,
  address TEXT,
  occupation TEXT,
  company TEXT,
  website TEXT,
  country TEXT,
  bio TEXT,
  role TEXT NOT NULL DEFAULT user,
  dateupdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  datecreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  authors INTEGER NOT NULL,
  title TEXT NOT NULL,
  summary TEXT,
  post TEXT,
  image TEXT,
  video TEXT,
  thumbnail TEXT,
  tag TEXT NOT NULL,
  slug TEXT NOT NULL,
  draft BOOLEAN DEFAULT FALSE,
  next TEXT, 
  prev TEXT,
  dateupdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  datecreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (authors) REFERENCES users (id)
);

CREATE TABLE comments (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL, 
message TEXT NOT NULL, 
likes INTEGER DEFAULT 0, 
loves INTEGER DEFAULT 0,
dislikes INTEGER DEFAULT 0, 
path TEXT NOT NULL,
dateupdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
datecreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects (
id INTEGER PRIMARY KEY AUTOINCREMENT,
platform TEXT NOT NULL,
title TEXT NOT NULL, 
description TEXT, 
url TEXT,
src TEXT,
repo TEXT,
builtwith TEXT NOT NULL,
dateupdated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
datecreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)